### ISSUE TITLE
Make a new contact page 

### ISSUE THREAD

**Issue by jaripacheco** [jaripacheco/jaripacheco.github.io#4]
Make contact page, and make it similar to the photos page.

**Comment by jaripacheco** [comment]
@tommymetz

**Comment by tommymetz** [comment]
You have everything you need to make a new contact page. Just like the photos page, you can copy the `index.html` file and rename it `contact.html`. Or maybe duplicate the `photos.html` file instead if you want it to be more like that page. Then start editing that file to make it look the way you want. Then figure out how you can add it to the nav bar so that button links over to the contact page.

**Comment by jaripacheco** [comment]
@tommymetz thank you I solved it.

**Comment by tommymetz** [comment]
@jaripacheco nice work!
